
using System.IO;

namespace DotnetMigratorCLI.Services
{
    public static class ReportGenerator
    {
        public static void Run(string path)
        {
            Console.WriteLine($"[ReportGenerator] Generating migration report for {path}...");

            string report = $@"
# Migration Report for `{path}`

**Target Framework**: .NET 8  
**Detected Framework**: .NET Framework 4.6.1

## 📦 Dependencies
- Newtonsoft.Json (v10.0.3)
- EntityFramework (v6.2.0)

## ⚠️ Migration Issues
- `HttpContext.Current` is deprecated
- `WebForms` is not supported in .NET Core
- `AppDomain` usage needs review

## 🚧 Blockers
- COM Interop detected
- Legacy Crystal Reports integration
## ✅ Suggested Next Steps
- Replace `HttpContext.Current` with `IHttpContextAccessor`
- Migrate EF6 to EF Core
- Replace Crystal Reports with RDLC or Power BI Embedded

---

*Generated by DotnetMigratorCLI*
";

            Directory.CreateDirectory("output");
            File.WriteAllText("output/migration_report.md", report);
            Console.WriteLine("✅ Report saved to output/migration_report.md");
        }
    }
}
